// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxC2RtCe7Wf2TH9wT6TVx5W72KPFbJdok',
    appId: '1:605336652367:web:2268b337e0e9f0dda8b83a',
    messagingSenderId: '605336652367',
    projectId: 'moja-budowa123a',
    authDomain: 'moja-budowa123a.firebaseapp.com',
    storageBucket: 'moja-budowa123a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7AIx0eZXq4DctEMQPZSXfrUj9BI6zPFg',
    appId: '1:605336652367:android:88d658b637414b8ca8b83a',
    messagingSenderId: '605336652367',
    projectId: 'moja-budowa123a',
    storageBucket: 'moja-budowa123a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO6TqYdMJp_jcS_czbOhLcCLwLq23eW_0',
    appId: '1:605336652367:ios:9e65153d245b4a9ea8b83a',
    messagingSenderId: '605336652367',
    projectId: 'moja-budowa123a',
    storageBucket: 'moja-budowa123a.appspot.com',
    iosClientId: '605336652367-42i9nltlff7p3725igo9qqgrhblnc7s5.apps.googleusercontent.com',
    iosBundleId: 'com.marcinplinta.mojaBudowa',
  );
}
